### ISSUE TITLE
Capitalization is inconsistent / makes odd choices plus other minor formatting fixups

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#388]
- [ ] Descriptive text - only Unable needs a capital

![screen shot 2018-04-26 at 13 40 04](https://user-images.githubusercontent.com/17229/39307133-f1f09424-4959-11e8-9fc8-fa9e282772f3.png)

- [ ] From is not a noun or the start of a sentence in the phrase `Remove from Bacteraemia` 
- [ ]  While we're there can it be `Remove from Bacteraemia list` ?
- [ ] And can the cancel button not be white on white? 

![screen shot 2018-04-26 at 13 48 57](https://user-images.githubusercontent.com/17229/39307205-14d1c7a6-495a-11e8-97b6-cc9056ddec75.png)

- [ ] Database is not the name of a thing in this context (Demographics modal)

![screen shot 2018-04-26 at 13 53 15](https://user-images.githubusercontent.com/17229/39307314-66678e70-495a-11e8-9b75-1d1e7f3ba221.png)

- [ ] Should pick one choice of capwords or capsentence for record panel titles 

![screen shot 2018-04-26 at 13 53 36](https://user-images.githubusercontent.com/17229/39307388-9497e16e-495a-11e8-9ff2-040af1ca7481.png)

- [ ] Can we lose the branch icon next to test names ? 

![screen shot 2018-04-26 at 13 50 40](https://user-images.githubusercontent.com/17229/39307438-b205caf4-495a-11e8-9454-f5ec07bde04a.png)

- [ ] We need an `&nbsp;` in between the icon and title here
- [ ] Same as capitalization for trends also obv.

![screen shot 2018-04-26 at 13 41 01](https://user-images.githubusercontent.com/17229/39307474-cbf634da-495a-11e8-8efc-e3d4116f0a0b.png)

**Comment by davidmiller** [comment]
>  Can we lose the branch icon next to test names ?
Now I know what this actually does, let's leave it... 

I think that both me and @pacharanero did not find it intuitive what that did - so maybe needs some text like (view raw) ?

**Comment by fredkingham** [comment]
Our cancel buttons are always white

<img width="309" alt="screen shot 2018-05-09 at 18 09 36" src="https://user-images.githubusercontent.com/2175455/39828781-2e3b810a-53b4-11e8-896b-5b94368e5fcd.png">

I would suggest we change it to a button default e.g.
<img width="231" alt="screen shot 2018-05-09 at 18 10 23" src="https://user-images.githubusercontent.com/2175455/39828821-4e83bb4e-53b4-11e8-8644-9e84d55d1b17.png">

but we should do this in opal, as otherwise other buttons are effected.
